<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Stanchik</Authors>
        <PackageId>BSTU.Results.Collection</PackageId>
        <Version>1.0.0</Version>
        <Description>Results collection service for REST API</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>