name: laba3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  archive: ^3.6.1
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  # Firebase dependencies
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_database: ^11.0.20
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.6
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/mountain.jpg
    - assets/forest.jpg
    - assets/beach.jpg

